### PR TITLE
Add cheermotes to `bits` events

### LINKED ISSUE #60: Bits without --message get a empty message
**Describe the bug**
When you simulate a bits event and don't provide a message then the text will really be empty.
A cheer message always has to contain at least the used cheer emote.

It's not possible to cheer without a message as the generated event when using bits without --message.

**To Reproduce**
`bits --channel name --bitscount 100`

**Expected behavior**
The message has to contain at least a cheer emote -> ie. `Cheer100` - it can't be empty.

### PR DESCRIPTION
**Pull request by trezy**
`bits` events now work as follows to determine the amount of bits sent and manipulate the message as necessary:

1. Search the message for Twitch supported cheermotes
1. Calculate the total number of bits sent
1. If no cheermotes present, check for a value in the `--bitscount` flag (defaults to 100) and add an appropriate cheermote

### SCENARIO 1: Cheermotes included in the message

**Input**
```js
client.say('#channel', 'bits foo bar Cheer4000 Cheer200')
```

**Response**
```
@bits=4200 :fdgt-test!fdgt-test@fdgt-test.tmi.twitch.tv PRIVMSG #fdgt :foo bar Cheer4000 Cheer200
```

### SCENARIO 2: Message with no cheermotes

**Input**
```js
client.say('#channel', 'bits foo bar')
```

**Response**
```
@bits=100 :fdgt-test!fdgt-test@fdgt-test.tmi.twitch.tv PRIVMSG #fdgt :foo bar cheer100
```

### SCENARIO 3: Using `--bitscount`

**Input**
```js
client.say('#channel', 'bits --bitscount 1234')
```

**Response**
```
@bits=1234 :fdgt-test!fdgt-test@fdgt-test.tmi.twitch.tv PRIVMSG #fdgt :cheer1234
```

### SCENARIO 4: Using defaults

**Input**
```js
client.say('#channel', 'bits')
```

**Response**
```
@bits=100 :fdgt-test!fdgt-test@fdgt-test.tmi.twitch.tv PRIVMSG #fdgt :cheer100
```

## Affected Issues
fixes #60

/cc @PhilippHeuer @iProdigy

### CODE REVIEW

**Comment by trezy** [comment]
@iProdigy Hmm... I'm not sure about that. I lean towards having cheermotes override `--bitscount` just to limit the amount of processing needed on the `fdgt` side. Since `fdgt` only selects valid cheermotes from the message (e.g. `cheer1234` is recognized, but `prodigy1234` is not), I don't see a scenario where somebody would provide invalid cheermotes being an issue.

I could, however, add some validation that only one method is used. If somebody includes cheermotes in the message *and* uses the `--bitscount` flag, we could respond with a message indicating that this isn't allowed. What are your thoughts on that?

**Comment by iProdigy** [comment]
I think just using the supplied `bitscount` would minimize processing on fdgt's side as there would be no need to call the regex matching code to find the cheermotes in the message

**Comment by trezy** [comment]
That's valid, but then code that processes the cheermotes from the message vs the `bits` flag would get different results. The only solution for that would be processing the message to *remove* user-sent cheermotes, attaching a new cheermote with the appropriate bits amount.

Maybe this isn't a common or realistic scenario, but I'm weary of having a response with two disparate values when that's not possible to accomplish via Twitch.

**Comment by iProdigy** [comment]
Yeah I don't think removing things from a user-specified message is great & this is a weird edge case anyways so I leave it up to you on how to handle ❤️

**Pull request merged**
